#version 450
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) readonly buffer Input { float in_data[]; };
layout(set = 0, binding = 1) writeonly buffer Output { float out_data[]; };

layout(push_constant) uniform PushConstants {
    uint size;
} params;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= params.size) return;
    
    out_data[idx] = floor(in_data[idx]);
}
